# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Sample React projects with Circle CI
# - https://github.com/CircleCI-Public/circleci-demo-javascript-react-app/blob/master/.circleci/config.yml
# - https://github.com/CircleCI-Public/circleci-demo-javascript-express/blob/master/.circleci/config.yml

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0

jobs:
  # placeholder for "test" job
  test:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
  build:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: sde-project
          tag: latest
  # placeholder for "deploy" job
  deploy:
    docker:
      - image: cimg/node:14.15.0
    steps:
      - checkout

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  ci-cd: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - test
      - build
      - deploy:
          requires:
            - test
            - build
